DRILL-1732 - rename drillbit.sh to just drillbit

diff --git a/distribution/src/resources/drillbit b/distribution/src/resources/drillbit
--- a/distribution/src/resources/drillbit
+++ b/distribution/src/resources/drillbit
@@ -1,166 +1,247 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
-# Licensed to the Apache Software Foundation (ASF) under one or more
-# contributor license agreements.  See the NOTICE file distributed with
-# this work for additional information regarding copyright ownership.
-# The ASF licenses this file to You under the Apache License, Version 2.0
-# (the "License"); you may not use this file except in compliance with
-# the License.  You may obtain a copy of the License at
+#/**
+# * Copyright 2013 The Apache Software Foundation
+# *
+# * Licensed to the Apache Software Foundation (ASF) under one
+# * or more contributor license agreements.  See the NOTICE file
+# * distributed with this work for additional information
+# * regarding copyright ownership.  The ASF licenses this file
+# * to you under the Apache License, Version 2.0 (the
+# * "License"); you may not use this file except in compliance
+# * with the License.  You may obtain a copy of the License at
+# *
+# *     http://www.apache.org/licenses/LICENSE-2.0
+# *
+# * Unless required by applicable law or agreed to in writing, software
+# * distributed under the License is distributed on an "AS IS" BASIS,
+# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# * See the License for the specific language governing permissions and
+# * limitations under the License.
+# */
+# 
+# Environment Variables
 #
-#     http://www.apache.org/licenses/LICENSE-2.0
+#   DRILL_CONF_DIR   Alternate drill conf dir. Default is ${DRILL_HOME}/conf.
+#   DRILL_LOG_DIR    Where log files are stored.  PWD by default.
+#   DRILL_PID_DIR    The pid files are stored. /tmp by default.
+#   DRILL_IDENT_STRING   A string representing this instance of drillbit. $USER by default
+#   DRILL_NICENESS The scheduling priority for daemons. Defaults to 0.
+#   DRILL_STOP_TIMEOUT  Time, in seconds, after which we kill -9 the server if it has not stopped.
+#                        Default 1200 seconds.
 #
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-#
-# Starts a Drillbit
-#
-# chkconfig: 345 85 15
-# description: Drillbit
-#
-### BEGIN INIT INFO
-# Provides:          drillbit
-# Short-Description: Drillbit
-# Default-Start:     3 4 5
-# Default-Stop:      0 1 2 6
-# Required-Start:    $syslog $remote_fs
-# Required-Stop:     $syslog $remote_fs
-# Should-Start:
-# Should-Stop:
-### END INIT INFO
+# Modelled after $HADOOP_HOME/bin/hadoop-daemon.sh
 
-. /lib/lsb/init-functions
-RETVAL_SUCCESS=0
+usage="Usage: drillbit [--config <conf-dir>]\
+ (start|stop|status|restart|autorestart)"
 
-STATUS_RUNNING=0
-STATUS_DEAD=1
-STATUS_DEAD_AND_LOCK=2
-STATUS_NOT_RUNNING=3
-STATUS_OTHER_ERROR=102
+# if no args specified, show usage
+if [ $# -lt 1 ]; then
+  echo $usage
+  exit 1
+fi
 
+bin=`dirname "${BASH_SOURCE-$0}"`
+bin=`cd "$bin">/dev/null; pwd`
 
-ERROR_PROGRAM_NOT_INSTALLED=5
-ERROR_PROGRAM_NOT_CONFIGURED=6
+. "$bin"/drill-config.sh
 
+# get arguments
+startStopStatus=$1
+shift
 
-RETVAL=0
-SLEEP_TIME=5
-PROC_NAME="java"
+command=drillbit
+shift
 
-DAEMON="drillbit"
-DESC="Drillbit"
-EXEC_PATH="/opt/drill/bin/drillbit.sh"
-SVC_USER=""
-DAEMON_FLAGS=""
-CONF_DIR="/etc/drill/conf"
-PIDFILE="/opt/drill/drillbit.pid"
-LOCKDIR="/var/lock/subsys"
-LOCKFILE="$LOCKDIR/drillbit"
-WORKING_DIR="~/"
-
-install -d -m 0755 -o  -g  /var/run/drillbit 1>/dev/null 2>&1 || :
-[ -d "$LOCKDIR" ] || install -d -m 0755 $LOCKDIR 1>/dev/null 2>&1 || :
-
-start() {
-  [ -x $EXEC_PATH ] || exit $ERROR_PROGRAM_NOT_INSTALLED
-  [ -d $CONF_DIR ] || exit $ERROR_PROGRAM_NOT_CONFIGURED
-  log_success_msg "Starting ${DESC}: "
-
-  su -s /bin/bash $SVC_USER -c "cd $WORKING_DIR && $EXEC_PATH --config '$CONF_DIR' start $DAEMON_FLAGS"
-
-  # Some processes are slow to start
-  sleep $SLEEP_TIME
-  checkstatusofproc
-  RETVAL=$?
-
-  [ $RETVAL -eq $RETVAL_SUCCESS ] && touch $LOCKFILE
-  return $RETVAL
-}
-
-
-stop() {
-  log_success_msg "Stopping ${DESC}: "
-  start_daemon $EXEC_PATH --config "$CONF_DIR" stop $DAEMON_FLAGS
-  RETVAL=$?
-
-  [ $RETVAL -eq $RETVAL_SUCCESS ] && rm -f $LOCKFILE $PIDFILE
-}
-
-restart() {
-  stop
-  start
-}
-
-checkstatusofproc(){
-  pidofproc -p $PIDFILE $PROC_NAME > /dev/null
-}
-
-checkstatus(){
-  checkstatusofproc
-  status=$?
-
-  case "$status" in
-    $STATUS_RUNNING)
-      log_success_msg "${DESC} is running"
-      ;;
-    $STATUS_DEAD)
-      log_failure_msg "${DESC} is dead and pid file exists"
-      ;;
-    $STATUS_DEAD_AND_LOCK)
-      log_failure_msg "${DESC} is dead and lock file exists"
-      ;;
-    $STATUS_NOT_RUNNING)
-      log_failure_msg "${DESC} is not running"
-      ;;
-    *)
-      log_failure_msg "${DESC} status is unknown"
-      ;;
-  esac
-  return $status
-}
-
-condrestart(){
-  [ -e $LOCKFILE ] && restart || :
-}
-
-check_for_root() {
-  if [ $(id -ur) -ne 0 ]; then
-    echo 'Error: root user required'
-    echo
-    exit 1
+waitForProcessEnd() {
+  pidKilled=$1
+  commandName=$2
+  processedAt=`date +%s`
+  while kill -0 $pidKilled > /dev/null 2>&1;
+   do
+     echo -n "."
+     sleep 1;
+     # if process persists more than $DRILL_STOP_TIMEOUT (default 1200 sec) no mercy
+     if [ $(( `date +%s` - $processedAt )) -gt ${DRILL_STOP_TIMEOUT:-1200} ]; then
+       break;
+     fi
+   done
+  # process still there : kill -9
+  if kill -0 $pidKilled > /dev/null 2>&1; then
+    echo -n force stopping $commandName with kill -9 $pidKilled
+    $JAVA_HOME/bin/jstack -l $pidKilled > "$logout" 2>&1
+    kill -9 $pidKilled > /dev/null 2>&1
   fi
+  # Add a CR after we're done w/ dots.
+  echo
 }
 
-service() {
-  case "$1" in
-    start)
-      check_for_root
-      start
-      ;;
-    stop)
-      check_for_root
-      stop
-      ;;
-    status)
-      checkstatus
-      RETVAL=$?
-      ;;
-    restart)
-      check_for_root
-      restart
-      ;;
-    condrestart|try-restart)
-      check_for_root
-      condrestart
-      ;;
-    *)
-      echo $"Usage: $0 {start|stop|status|restart|try-restart|condrestart}"
-      exit 1
-  esac
+drill_rotate_log ()
+{
+    log=$1;
+    num=5;
+    if [ -n "$2" ]; then
+    num=$2
+    fi
+    if [ -f "$log" ]; then # rotate logs
+    while [ $num -gt 1 ]; do
+        prev=`expr $num - 1`
+        [ -f "$log.$prev" ] && mv -f "$log.$prev" "$log.$num"
+        num=$prev
+    done
+    mv -f "$log" "$log.$num";
+    fi
 }
 
-service "$1"
+check_before_start(){
+    #ckeck if the process is not running
+    mkdir -p "$DRILL_PID_DIR"
+    if [ -f $pid ]; then
+      if kill -0 `cat $pid` > /dev/null 2>&1; then
+        echo $command running as process `cat $pid`.  Stop it first.
+        exit 1
+      fi
+    fi
+}
 
-exit $RETVAL
+wait_until_done ()
+{
+    p=$1
+    cnt=${DRILLBIT_TIMEOUT:-300}
+    origcnt=$cnt
+    while kill -0 $p > /dev/null 2>&1; do
+      if [ $cnt -gt 1 ]; then
+        cnt=`expr $cnt - 1`
+        sleep 1
+      else
+        echo "Process did not complete after $origcnt seconds, killing."
+        kill -9 $p
+        exit 1
+      fi
+    done
+    return 0
+}
+
+# get log directory
+if [ "$DRILL_LOG_DIR" = "" ]; then
+  export DRILL_LOG_DIR=/var/log/drill
+fi
+mkdir -p "$DRILL_LOG_DIR"
+
+if [ "$DRILL_PID_DIR" = "" ]; then
+  DRILL_PID_DIR=$DRILL_HOME
+fi
+
+# Some variables
+# Work out java location so can print version into log.
+if [ "$JAVA_HOME" != "" ]; then
+  #echo "run java in $JAVA_HOME"
+  JAVA_HOME=$JAVA_HOME
+fi
+if [ "$JAVA_HOME" = "" ]; then
+  echo "Error: JAVA_HOME is not set."
+  exit 1
+fi
+
+JAVA=$JAVA_HOME/bin/java
+export DRILL_LOG_PREFIX=drillbit
+export DRILL_LOGFILE=$DRILL_LOG_PREFIX.log
+export DRILL_OUTFILE=$DRILL_LOG_PREFIX.out
+loggc=$DRILL_LOG_DIR/$DRILL_LOG_PREFIX.gc
+loglog="${DRILL_LOG_DIR}/${DRILL_LOGFILE}"
+logout="${DRILL_LOG_DIR}/${DRILL_OUTFILE}"
+pid=$DRILL_PID_DIR/drillbit.pid
+
+export DRILLBIT_LOG_PATH=$loglog
+
+if [ -n "$SERVER_GC_OPTS" ]; then
+  export SERVER_GC_OPTS=${SERVER_GC_OPTS/"-Xloggc:<FILE-PATH>"/"-Xloggc:${loggc}"}
+fi
+if [ -n "$CLIENT_GC_OPTS" ]; then
+  export CLIENT_GC_OPTS=${CLIENT_GC_OPTS/"-Xloggc:<FILE-PATH>"/"-Xloggc:${loggc}"}
+fi
+
+# Set default scheduling priority
+if [ "$DRILL_NICENESS" = "" ]; then
+    export DRILL_NICENESS=0
+fi
+
+thiscmd=$0
+args=$@
+
+case $startStopStatus in
+
+(start)
+    check_before_start
+    echo starting $command, logging to $logout
+    nohup $thiscmd internal_start $command $args < /dev/null >> ${logout} 2>&1  &
+    sleep 1;
+  ;;
+
+(internal_start)
+    drill_rotate_log $loggc
+    # Add to the command log file vital stats on our environment.
+    echo "`date` Starting $command on `hostname`" >> $loglog
+    echo "`ulimit -a`" >> $loglog 2>&1
+    nice -n $DRILL_NICENESS "$DRILL_HOME"/bin/runbit \
+        $command "$@" start >> "$logout" 2>&1 &
+    echo $! > $pid
+    wait
+  ;;
+
+(stop)
+    rm -f "$DRILL_START_FILE"
+    if [ -f $pid ]; then
+      pidToKill=`cat $pid`
+      # kill -0 == see if the PID exists
+      if kill -0 $pidToKill > /dev/null 2>&1; then
+        echo stopping $command
+        echo "`date` Terminating $command" pid $pidToKill>> $loglog
+        kill $pidToKill > /dev/null 2>&1
+        waitForProcessEnd $pidToKill $command
+        rm $pid
+      else
+        retval=$?
+        echo no $command to stop because kill -0 of pid $pidToKill failed with status $retval
+      fi
+    else
+      echo no $command to stop because no pid file $pid
+    fi
+  ;;
+
+(restart)
+    # stop the command
+    $thiscmd --config "${DRILL_CONF_DIR}" stop $command $args &
+    wait_until_done $!
+    # wait a user-specified sleep period
+    sp=${DRILL_RESTART_SLEEP:-3}
+    if [ $sp -gt 0 ]; then
+      sleep $sp
+    fi
+    # start the command
+    $thiscmd --config "${DRILL_CONF_DIR}" start $command $args &
+    wait_until_done $!
+  ;;
+
+(status)
+
+    if [ -f $pid ]; then
+      TARGET_PID=`cat $pid`
+      if kill -0 $TARGET_PID > /dev/null 2>&1; then
+        echo $command is running.
+        exit 0
+      else
+        echo $pid file is present but $command not running.
+        exit 1
+      fi
+    else
+      echo $command not running.
+      exit 2
+    fi
+    ;;
+
+(*)
+  echo $usage
+  exit 1
+  ;;
+esac
